# Generated by Django 5.2.3 on 2025-06-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todolist_app", "0002_tasklist_manage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklist",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
